### ISSUE TITLE
0.1.0 does not work in Thebe

### ISSUE THREAD

**Issue by sandertyu** [LibreTexts/jupyterteam_widget#3]
Using `interact.html` and an http server, I tested the 0.1.0 tag of this repository using Thebe and got "Error displaying widget" errors in the output box, and the following in console;

![widget-error-console](https://cdn.discordapp.com/attachments/729801592433410138/859710706056560660/unknown.png)

Launching the same tag on binder.libretexts.org and using example-notebook.ipynb, our widget runs fine, so the issue is certainly Thebe.

**Comment by sandertyu** [comment]
fixed by locally symlinking to `js/dist/index,js` which is necessary for Thebe to access from within the web page. the alternative is posting it to unpkg.

**Comment by moorepants** [comment]
What is index.js, is that something that is included with thebe?

**Comment by TimStewartJ** [comment]
Index.js is the built widget; It is generated when you run `yarn build`.
